# Create SMSTO DB
CREATE DATABASE IF NOT EXISTS j3 /*\!40100 DEFAULT CHARACTER SET utf8 */;
CREATE USER IF NOT EXISTS j3@'%' IDENTIFIED BY 'j3';
GRANT ALL PRIVILEGES ON j3.* TO 'j3'@'%';

# Reload privileges
FLUSH PRIVILEGES;
